const API='https://eth.blockscout.com/api/v2';
let state={root:'',depth:3,txs:[],nodes:new Map(),alerts:[],risk:0};
const $=id=>document.getElementById(id);
function showView(id,btn){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active')}
function short(x){return x?x.slice(0,7)+'…'+x.slice(-5):'—'}
function eth(v){return (Number(v||0)/1e18).toFixed(5)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function api(path){const r=await fetch(API+path);if(!r.ok)throw new Error('Blockchain API returned '+r.status);return r.json()}
function normalizeTx(t){return {hash:t.hash,from:(t.from?.hash||'').toLowerCase(),to:(t.to?.hash||'').toLowerCase(),value:Number(t.value||0),time:t.timestamp||'',block:t.block_number||0}}
function scoreNode(addr,txs){const a=txs.filter(t=>t.from===addr||t.to===addr);const outs=a.filter(t=>t.from===addr),ins=a.filter(t=>t.to===addr);const peers=new Set(a.map(t=>t.from===addr?t.to:t.from).filter(Boolean));let s=0;if(a.length>=20)s+=15;if(a.length>=50)s+=15;if(peers.size>=10)s+=15;if(peers.size>=25)s+=15;if(outs.length>=10)s+=10;const times=a.map(t=>Date.parse(t.time)).filter(Boolean).sort((x,y)=>x-y);let rapid=0;for(let i=1;i<times.length;i++)if(times[i]-times[i-1]<120000)rapid++;if(rapid>=3)s+=15;return Math.min(100,s)}
function buildGraph(rootTxs,root){state.nodes=new Map();rootTxs.forEach(t=>{if(t.from)state.nodes.set(t.from,{addr:t.from,txs:[],risk:0});if(t.to)state.nodes.set(t.to,{addr:t.to,txs:[],risk:0});if(t.from)state.nodes.get(t.from).txs.push(t);if(t.to)state.nodes.get(t.to).txs.push(t)});state.nodes.forEach(n=>n.risk=scoreNode(n.addr,rootTxs));state.alerts=[];state.nodes.forEach(n=>{if(n.risk>=60)state.alerts.push({level:n.risk>=80?'CRITICAL':'HIGH',title:'Elevated transaction-network risk',addr:n.addr,reason:`${n.txs.length} observed transactions and ${new Set(n.txs.map(t=>t.from===n.addr?t.to:t.from)).size} counterparties.`})});state.risk=state.nodes.get(root)?.risk||scoreNode(root,rootTxs);}
function renderGraph(){const svg=$('svg');svg.innerHTML='';const ns='http://www.w3.org/2000/svg';const nodes=[...state.nodes.values()].slice(0,18);if(!nodes.length)return;const root=state.root.toLowerCase();const center=nodes.find(n=>n.addr===root)||nodes[0];const others=nodes.filter(n=>n!==center);center.x=380;center.y=250;others.forEach((n,i)=>{const a=i/Math.max(1,others.length)*Math.PI*2;n.x=380+Math.cos(a)*260;n.y=250+Math.sin(a)*190});const marker=document.createElementNS(ns,'marker');marker.setAttribute('id','arrow');marker.setAttribute('viewBox','0 0 10 10');marker.setAttribute('refX','9');marker.setAttribute('refY','5');marker.setAttribute('markerWidth','5');marker.setAttribute('markerHeight','5');marker.setAttribute('orient','auto');const p=document.createElementNS(ns,'path');p.setAttribute('d','M0 0L10 5L0 10z');p.setAttribute('fill','#526b7d');marker.appendChild(p);const defs=document.createElementNS(ns,'defs');defs.appendChild(marker);svg.appendChild(defs);const pos=new Map(nodes.map(n=>[n.addr,n]));state.txs.slice(0,40).forEach(t=>{const a=pos.get(t.from),b=pos.get(t.to);if(!a||!b)return;const l=document.createElementNS(ns,'line');Object.entries({x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:'#385263','stroke-width':'1.5','marker-end':'url(#arrow)'}).forEach(([k,v])=>l.setAttribute(k,v));svg.appendChild(l)});nodes.forEach(n=>{const g=document.createElementNS(ns,'g');g.style.cursor='pointer';const c=document.createElementNS(ns,'circle');c.setAttribute('cx',n.x);c.setAttribute('cy',n.y);c.setAttribute('r',n===center?27:21);c.setAttribute('fill','#08131b');c.setAttribute('stroke',n.risk>=60?'#ff647c':n.risk>=30?'#ffbd59':'#55d6be');c.setAttribute('stroke-width','3');g.appendChild(c);const t=document.createElementNS(ns,'text');t.setAttribute('x',n.x);t.setAttribute('y',n.y+4);t.setAttribute('text-anchor','middle');t.setAttribute('class','svgtext');t.textContent=n===center?'ROOT':String.fromCharCode(65+nodes.indexOf(n));g.appendChild(t);const l=document.createElementNS(ns,'text');l.setAttribute('x',n.x);l.setAttribute('y',n.y+38);l.setAttribute('text-anchor','middle');l.setAttribute('class','edgeLabel');l.textContent=short(n.addr);g.appendChild(l);g.onclick=()=>selectNode(n);svg.appendChild(g)})}
function selectNode(n){const risk=n.risk;const level=risk>=80?'CRITICAL':risk>=60?'HIGH':risk>=30?'MEDIUM':'LOW';$('walletBox').innerHTML=`<div class="riskTop"><div><div class="label">Wallet</div><div class="mono">${esc(n.addr)}</div></div><span class="pill ${level==='HIGH'||level==='CRITICAL'?'high':level==='MEDIUM'?'medium':'low'}">${level}</span></div><div class="value">${risk}<span class="hint">/100</span></div><div class="bar"><i style="width:${risk}%"></i></div><div class="kv"><div><b>${n.txs.length}</b><span>Observed txns</span></div><div><b>${new Set(n.txs.map(t=>t.from===n.addr?t.to:t.from)).size}</b><span>Counterparties</span></div><div><b>${(n.txs.filter(t=>t.to===n.addr).reduce((s,t)=>s+t.value,0)/1e18).toFixed(4)} ETH</b><span>Incoming</span></div><div><b>${(n.txs.filter(t=>t.from===n.addr).reduce((s,t)=>s+t.value,0)/1e18).toFixed(4)} ETH</b><span>Outgoing</span></div></div>`}
function renderTable(){const rows=state.txs.slice(0,40);$('txTable').innerHTML=rows.map(t=>{const r=scoreNode(t.from,state.txs);const level=r>=60?'HIGH':r>=30?'MEDIUM':'LOW';return `<tr><td>${esc(t.time||'—')}</td><td class="mono">${esc(short(t.hash))}</td><td class="mono">${esc(short(t.from))}</td><td class="mono">${esc(short(t.to))}</td><td>${eth(t.value)} ETH</td><td><span class="status ${level.toLowerCase()}">${level}</span></td></tr>`}).join('')||'<tr><td colspan="6">No transactions returned.</td></tr>'}
function renderStats(){ $('statNodes').textContent=state.nodes.size; $('statTx').textContent=state.txs.length; $('statAlerts').textContent=state.alerts.length; $('statValue').textContent=(state.txs.reduce((s,t)=>s+t.value,0)/1e18).toFixed(2)+' ETH'; $('patternBox').innerHTML=state.alerts.length?state.alerts.slice(0,5).map(a=>`<div class="alert"><b>${a.level} · ${esc(a.title)}</b><span class="mono">${esc(short(a.addr))}</span> — ${esc(a.reason)}</div>`).join(''):'No elevated patterns detected by the current heuristic engine.'; $('alertsList').innerHTML=state.alerts.length?state.alerts.map(a=>`<div class="alert"><b>${a.level} · ${esc(a.title)}</b><span class="mono">${esc(a.addr)}</span> — ${esc(a.reason)}</div>`).join(''):'<div class="hint">No elevated patterns detected.</div>' }
async function loadWallet(addr,depth){state.root=addr.toLowerCase();let all=[],front=[state.root],seen=new Set(front);for(let d=0;d<depth;d++){const next=new Set();for(const a of front){const data=await api(`/addresses/${a}/transactions?filter=validated&page_size=100`);const txs=(data.items||[]).map(normalizeTx);all.push(...txs);txs.forEach(t=>{[t.from,t.to].forEach(x=>{if(x&&!seen.has(x)&&x!==state.root){seen.add(x);next.add(x)}})});if(seen.size>18)break}front=[...next].slice(0,6);if(!front.length||seen.size>18)break}const uniq=[...new Map(all.filter(t=>t.hash).map(t=>[t.hash,t])).values()];state.txs=uniq;buildGraph(uniq,state.root);renderStats();renderGraph();renderTable();$('statAlerts').textContent=state.alerts.length;selectNode(state.nodes.get(state.root)||[...state.nodes.values()][0]);$('investigationResult').style.display='block';$('liveDepth').textContent=depth+' hops';$('liveNodes').textContent=state.nodes.size;$('liveAlerts').textContent=state.alerts.length;$('liveRisk').textContent=state.risk+'/100';$('liveSummary').textContent=`Retrieved ${uniq.length} unique Ethereum transactions across ${state.nodes.size} observed addresses.`;$('reportSubject').textContent=state.root;$('reportRisk').textContent=state.risk+'/100';$('reportTrace').textContent=`${depth} hops / ${state.nodes.size} nodes`;}
async function runInvestigation(){const q=$('query').value.trim().toLowerCase();const d=Number($('depth').value);const st=$('traceStatus');st.style.display='block';if(!/^0x[a-f0-9]{40}$/.test(q)){st.textContent='Enter a valid Ethereum wallet address (0x + 40 hexadecimal characters). Transaction-hash tracing is supported as a single-transaction lookup in the next backend stage.';return}try{st.textContent='Querying Ethereum…';await loadWallet(q,d);st.style.display='none';showView('dashboard',document.querySelector('.nav button'));}catch(e){st.textContent='Live lookup failed: '+e.message+'. Try again or verify the wallet address.'}}
function downloadReport(){const html='<!doctype html><html><body style="font-family:Arial;max-width:900px;margin:40px auto"><h1>ChainSight Investigation Report</h1>'+$('reportContent').innerHTML+'</body></html>';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([html],{type:'text/html'}));a.download='ChainSight-Investigation-Report.html';a.click()}
$('statNodes').textContent='—';$('statTx').textContent='—';$('statAlerts').textContent='—';$('statValue').textContent='—';
